### ISSUE TITLE
Turn off top factors

### ISSUE THREAD

**Issue by mmastand** [HealthCatalyst/healthcareai-py#461] opened 2017-12-28 18:38 UTC
It would really help with speed for the package on 1M+ rows if we could turn off the top factors calculation. The overhead of doing both model trainings is really rough when models take hours to train.

Without knowing the architecture of the package completely, perhaps an input flag `streamline == True` could turn off some of the more extraneous and computationally expensive things?

**Comment by Aylr** [comment] 2017-12-29 15:33
Likely a duplicate of [419](https://github.com/HealthCatalyst/healthcareai-py/issues/419)

**Comment by Aylr** [comment] 2018-01-22 16:37
Dupe. Closing

**Closed by Aylr** 2018-01-22 16:37 UTC
